service: awsoneTelebot

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}



functions:
  post:
    handler: handler.hello
    events:
      - http:
          path: secret-hook-for-telegram
          method: post
          cors: true
